import { Json } from './auth-types';

export interface MaintenanceSchema {
  Tables: {
    maintenance_requests: {
      Row: {
        id: string;
        property_id: string;
        tenant_id: string;
        title: string;
        description: string;
        status: 'pending' | 'in_progress' | 'completed' | 'cancelled';
        created_at: string;
        updated_at: string;
        issue_type: string | null;
        priority: 'low' | 'medium' | 'high' | null;
        images: string[] | null;
        notes: string | null;
        assigned_to: string | null;
        service_provider_notes: string | null;
        read_by_landlord: boolean | null;
        read_by_tenant: boolean | null;
        service_provider_fee: number | null;
        service_provider_status: string | null;
        scheduled_date: string | null;
        completion_report: string | null;
        completion_date: string | null;
        payment_status: string | null;
        payment_amount: number | null;
        rating: number | null;
        rating_comment: string | null;
        cost_estimate: number | null;
        cost_estimate_status: string | null;
        cost_estimate_notes: string | null;
        approval_status: string | null;
        approval_notes: string | null;
        recurring_schedule: Json | null;
        next_scheduled_date: string | null;
        materials_cost: number | null;
      };
      Insert: {
        id?: string;
        property_id: string;
        tenant_id: string;
        title: string;
        description: string;
        status?: 'pending' | 'in_progress' | 'completed' | 'cancelled';
        created_at?: string;
        updated_at?: string;
        issue_type?: string | null;
        priority?: 'low' | 'medium' | 'high' | null;
        images?: string[] | null;
        notes?: string | null;
        assigned_to?: string | null;
        service_provider_notes?: string | null;
        read_by_landlord?: boolean | null;
        read_by_tenant?: boolean | null;
        service_provider_fee?: number | null;
        service_provider_status?: string | null;
        scheduled_date?: string | null;
        completion_report?: string | null;
        completion_date?: string | null;
        payment_status?: string | null;
        payment_amount?: number | null;
        rating?: number | null;
        rating_comment?: string | null;
        cost_estimate?: number | null;
        cost_estimate_status?: string | null;
        cost_estimate_notes?: string | null;
        approval_status?: string | null;
        approval_notes?: string | null;
        recurring_schedule?: Json | null;
        next_scheduled_date?: string | null;
        materials_cost?: number | null;
      };
      Update: {
        id?: string;
        property_id?: string;
        tenant_id?: string;
        title?: string;
        description?: string;
        status?: 'pending' | 'in_progress' | 'completed' | 'cancelled';
        created_at?: string;
        updated_at?: string;
        issue_type?: string | null;
        priority?: 'low' | 'medium' | 'high' | null;
        images?: string[] | null;
        notes?: string | null;
        assigned_to?: string | null;
        service_provider_notes?: string | null;
        read_by_landlord?: boolean | null;
        read_by_tenant?: boolean | null;
        service_provider_fee?: number | null;
        service_provider_status?: string | null;
        scheduled_date?: string | null;
        completion_report?: string | null;
        completion_date?: string | null;
        payment_status?: string | null;
        payment_amount?: number | null;
        rating?: number | null;
        rating_comment?: string | null;
        cost_estimate?: number | null;
        cost_estimate_status?: string | null;
        cost_estimate_notes?: string | null;
        approval_status?: string | null;
        approval_notes?: string | null;
        recurring_schedule?: Json | null;
        next_scheduled_date?: string | null;
        materials_cost?: number | null;
      };
    };
  };
}